### ISSUE TITLE
missing code of "chemprop" class

### ISSUE THREAD

**Issue by jmlongriver** [wengong-jin/DSMBind#5]
I got an error as below:

File "tutorial.py", line 7, in <module>
    from bindenergy.models import DrugAllAtomEnergyModel
  File "/DSMBind/bindenergy/models/__init__.py", line 3, in <module>
    from .drug import *
  File "/DSMBind/bindenergy/models/drug.py", line 9, in <module>
    from chemprop.features import BatchMolGraph, get_atom_fdim, get_bond_fdim, mol2graph
ModuleNotFoundError: No module named 'chemprop'

cannot find any class definition of "chemprop", could you please help on it? thanks

**Comment by lizongquan01** [comment]
> I got an error as below:
> 
> File "tutorial.py", line 7, in from bindenergy.models import DrugAllAtomEnergyModel File "/DSMBind/bindenergy/models/**init**.py", line 3, in from .drug import * File "/DSMBind/bindenergy/models/drug.py", line 9, in from chemprop.features import BatchMolGraph, get_atom_fdim, get_bond_fdim, mol2graph ModuleNotFoundError: No module named 'chemprop'
> 
> cannot find any class definition of "chemprop", could you please help on it? thanks

Hi jmlongriver,
  Actually, this chemprop is a package, you can use "pip install pip install chemprop" to get it. Just take a try!

**Comment by wengong-jin** [comment]
Sorry yes please install chemprop using `pip install chemprop`. I have updated the README.
